Repository evrentan/community-workspace, pull requests merged in 2024-02, with the labels that each got.

#122 chore(documentation_request): update title and labels
  .github/ISSUE_TEMPLATE/documentation_request.md
Labels: chore

#121 [Feature]: Community Manager Exception Class Create
  community-manager/src/main/java/evrentan/community/communitymanager/exception/CustomRestError.java
  community-manager/src/main/java/evrentan/community/communitymanager/exception/GlobalRestExceptionHandler.java
Labels: enhancement

#123 feat(dto): refactor dto structure
  community-manager/src/main/java/evrentan/community/communitymanager/controller/CommunityController.java
  community-manager/src/main/java/evrentan/community/communitymanager/dto/entity/Community.java
  community-manager/src/main/java/evrentan/community/communitymanager/dto/exception/CustomRestError.java
  community-manager/src/main/java/evrentan/community/communitymanager/dto/other/MyConfigurationProperty.java
  community-manager/src/main/java/evrentan/community/communitymanager/entity/CommunityEntity.java
  community-manager/src/main/java/evrentan/community/communitymanager/exception/GlobalRestExceptionHandler.java
  community-manager/src/main/java/evrentan/community/communitymanager/impl/CommunityServiceImpl.java
  community-manager/src/main/java/evrentan/community/communitymanager/impl/TestServiceImpl.java
  community-manager/src/main/java/evrentan/community/communitymanager/mapper/CommunityMapper.java
  community-manager/src/main/java/evrentan/community/communitymanager/service/CommunityService.java
  user-manager/src/main/java/evrentan/community/usermanager/controller/ApplicationUserController.java
  user-manager/src/main/java/evrentan/community/usermanager/controller/UserTypeController.java
  user-manager/src/main/java/evrentan/community/usermanager/dto/entity/ApplicationUser.java
  user-manager/src/main/java/evrentan/community/usermanager/dto/entity/UserType.java
  user-manager/src/main/java/evrentan/community/usermanager/entity/ApplicationUserEntity.java
  user-manager/src/main/java/evrentan/community/usermanager/entity/UserTypeEntity.java
  user-manager/src/main/java/evrentan/community/usermanager/impl/ApplicationUserServiceImpl.java
  user-manager/src/main/java/evrentan/community/usermanager/impl/UserTypeServiceImpl.java
  user-manager/src/main/java/evrentan/community/usermanager/mapper/ApplicationUserMapper.java
  user-manager/src/main/java/evrentan/community/usermanager/mapper/UserTypeMapper.java
  user-manager/src/main/java/evrentan/community/usermanager/service/ApplicationUserService.java
  user-manager/src/main/java/evrentan/community/usermanager/service/UserTypeService.java
  venue-manager/src/main/java/evrentan/community/venuemanager/controller/RoomController.java
  venue-manager/src/main/java/evrentan/community/venuemanager/controller/VenueController.java
  venue-manager/src/main/java/evrentan/community/venuemanager/dto/entity/Room.java
  venue-manager/src/main/java/evrentan/community/venuemanager/dto/entity/Venue.java
  venue-manager/src/main/java/evrentan/community/venuemanager/dto/entity/VenueRoom.java
  venue-manager/src/main/java/evrentan/community/venuemanager/entity/RoomEntity.java
  venue-manager/src/main/java/evrentan/community/venuemanager/entity/VenueEntity.java
  venue-manager/src/main/java/evrentan/community/venuemanager/entity/VenueRoomEntity.java
  venue-manager/src/main/java/evrentan/community/venuemanager/impl/RoomServiceImpl.java
  venue-manager/src/main/java/evrentan/community/venuemanager/impl/VenueServiceImpl.java
  venue-manager/src/main/java/evrentan/community/venuemanager/mapper/RoomMapper.java
  venue-manager/src/main/java/evrentan/community/venuemanager/mapper/VenueMapper.java
  venue-manager/src/main/java/evrentan/community/venuemanager/mapper/VenueRoomMapper.java
  venue-manager/src/main/java/evrentan/community/venuemanager/service/RoomService.java
  venue-manager/src/main/java/evrentan/community/venuemanager/service/VenueService.java
Labels: enhancement

#125 feat(exception): segregate community manager exceptions
  community-manager/src/main/java/evrentan/community/communitymanager/exception/CommunityNotFoundException.java
  community-manager/src/main/java/evrentan/community/communitymanager/exception/GlobalRestExceptionHandler.java
  community-manager/src/main/java/evrentan/community/communitymanager/impl/CommunityServiceImpl.java
  community-manager/src/main/java/evrentan/community/communitymanager/message/ExceptionMessages.java
Labels: enhancement

#128 fix(ApplicationUserServiceImpl): add UserAlreadyExistsException
  user-manager/src/main/java/evrentan/community/usermanager/exception/GlobalRestExceptionHandler.java
  user-manager/src/main/java/evrentan/community/usermanager/exception/UserAlreadyExistsException.java
  user-manager/src/main/java/evrentan/community/usermanager/impl/ApplicationUserServiceImpl.java
  user-manager/src/main/java/evrentan/community/usermanager/message/ExceptionMessages.java
Labels: bug

#130 feat(exception): segregate event manager exceptions
  event-manager/src/main/java/evrentan/community/eventmanager/dto/exception/CustomRestError.java
  event-manager/src/main/java/evrentan/community/eventmanager/exception/EventAlreadyExistsException.java
  event-manager/src/main/java/evrentan/community/eventmanager/exception/EventNotFoundException.java
  event-manager/src/main/java/evrentan/community/eventmanager/exception/GlobalRestExceptionHandler.java
  event-manager/src/main/java/evrentan/community/eventmanager/exception/IdNotMatchException.java
  event-manager/src/main/java/evrentan/community/eventmanager/message/ExceptionMessage.java
Labels: enhancement

#131 fix(CommunityServiceImpl): update community fix
  community-manager/src/main/java/evrentan/community/communitymanager/impl/CommunityServiceImpl.java
Labels: enhancement

#129 fix(EventServiceImpl): update event fix
  event-manager/src/main/java/evrentan/community/eventmanager/controller/EventController.java
  event-manager/src/main/java/evrentan/community/eventmanager/impl/EventServiceImpl.java
  event-manager/src/main/java/evrentan/community/eventmanager/service/EventService.java
Labels: bug
